### ISSUE TITLE
大佬，请问下有赞个人支付问题

### ISSUE THREAD

**Issue by yingziaxiba** [xu42/hiwifi-frpc#1]
我的能创建二维码，但是无法接收到支付状态，有赞推送日志  405错误。方便加个qq吗？
qq 191010848

**Comment by xu42** [comment]
@yingziaxiba 这个问题到 [xu42/pay](https://github.com/xu42/pay) 讨论吧。
确认有赞云后台的回调配置和你真实的接收消息的是一致的，需要查看下具体的报错信息才能定位问题。
